/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TenantIndexRouteImport } from './routes/tenant.index'
import { Route as ManagerIndexRouteImport } from './routes/manager.index'
import { Route as LandlordIndexRouteImport } from './routes/landlord.index'
import { Route as TenantReviewsRouteImport } from './routes/tenant.reviews'
import { Route as TenantRentRouteImport } from './routes/tenant.rent'
import { Route as TenantMaintenanceRouteImport } from './routes/tenant.maintenance'
import { Route as TenantLoanRouteImport } from './routes/tenant.loan'
import { Route as TenantDocumentsRouteImport } from './routes/tenant.documents'
import { Route as ManagerTenantsRouteImport } from './routes/manager.tenants'
import { Route as ManagerSettingsRouteImport } from './routes/manager.settings'
import { Route as ManagerReportsRouteImport } from './routes/manager.reports'
import { Route as ManagerPropertiesRouteImport } from './routes/manager.properties'
import { Route as ManagerNotificationsRouteImport } from './routes/manager.notifications'
import { Route as ManagerMaintenanceRouteImport } from './routes/manager.maintenance'
import { Route as ManagerFinancialsRouteImport } from './routes/manager.financials'
import { Route as ManagerEmailsRouteImport } from './routes/manager.emails'
import { Route as ManagerDocumentsRouteImport } from './routes/manager.documents'
import { Route as LandlordTenantsRouteImport } from './routes/landlord.tenants'
import { Route as LandlordPropertiesRouteImport } from './routes/landlord.properties'
import { Route as LandlordFinancialsRouteImport } from './routes/landlord.financials'
import { Route as LandlordDocumentsRouteImport } from './routes/landlord.documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIndexRoute = TenantIndexRouteImport.update({
  id: '/tenant/',
  path: '/tenant/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerIndexRoute = ManagerIndexRouteImport.update({
  id: '/manager/',
  path: '/manager/',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordIndexRoute = LandlordIndexRouteImport.update({
  id: '/landlord/',
  path: '/landlord/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantReviewsRoute = TenantReviewsRouteImport.update({
  id: '/tenant/reviews',
  path: '/tenant/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantRentRoute = TenantRentRouteImport.update({
  id: '/tenant/rent',
  path: '/tenant/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMaintenanceRoute = TenantMaintenanceRouteImport.update({
  id: '/tenant/maintenance',
  path: '/tenant/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantLoanRoute = TenantLoanRouteImport.update({
  id: '/tenant/loan',
  path: '/tenant/loan',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantDocumentsRoute = TenantDocumentsRouteImport.update({
  id: '/tenant/documents',
  path: '/tenant/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerTenantsRoute = ManagerTenantsRouteImport.update({
  id: '/manager/tenants',
  path: '/manager/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerSettingsRoute = ManagerSettingsRouteImport.update({
  id: '/manager/settings',
  path: '/manager/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerReportsRoute = ManagerReportsRouteImport.update({
  id: '/manager/reports',
  path: '/manager/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerPropertiesRoute = ManagerPropertiesRouteImport.update({
  id: '/manager/properties',
  path: '/manager/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerNotificationsRoute = ManagerNotificationsRouteImport.update({
  id: '/manager/notifications',
  path: '/manager/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerMaintenanceRoute = ManagerMaintenanceRouteImport.update({
  id: '/manager/maintenance',
  path: '/manager/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerFinancialsRoute = ManagerFinancialsRouteImport.update({
  id: '/manager/financials',
  path: '/manager/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerEmailsRoute = ManagerEmailsRouteImport.update({
  id: '/manager/emails',
  path: '/manager/emails',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagerDocumentsRoute = ManagerDocumentsRouteImport.update({
  id: '/manager/documents',
  path: '/manager/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordTenantsRoute = LandlordTenantsRouteImport.update({
  id: '/landlord/tenants',
  path: '/landlord/tenants',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordPropertiesRoute = LandlordPropertiesRouteImport.update({
  id: '/landlord/properties',
  path: '/landlord/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordFinancialsRoute = LandlordFinancialsRouteImport.update({
  id: '/landlord/financials',
  path: '/landlord/financials',
  getParentRoute: () => rootRouteImport,
} as any)
const LandlordDocumentsRoute = LandlordDocumentsRouteImport.update({
  id: '/landlord/documents',
  path: '/landlord/documents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/landlord/documents': typeof LandlordDocumentsRoute
  '/landlord/financials': typeof LandlordFinancialsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/emails': typeof ManagerEmailsRoute
  '/manager/financials': typeof ManagerFinancialsRoute
  '/manager/maintenance': typeof ManagerMaintenanceRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/properties': typeof ManagerPropertiesRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tenants': typeof ManagerTenantsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/loan': typeof TenantLoanRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/rent': typeof TenantRentRoute
  '/tenant/reviews': typeof TenantReviewsRoute
  '/landlord/': typeof LandlordIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/landlord/documents': typeof LandlordDocumentsRoute
  '/landlord/financials': typeof LandlordFinancialsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/emails': typeof ManagerEmailsRoute
  '/manager/financials': typeof ManagerFinancialsRoute
  '/manager/maintenance': typeof ManagerMaintenanceRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/properties': typeof ManagerPropertiesRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tenants': typeof ManagerTenantsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/loan': typeof TenantLoanRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/rent': typeof TenantRentRoute
  '/tenant/reviews': typeof TenantReviewsRoute
  '/landlord': typeof LandlordIndexRoute
  '/manager': typeof ManagerIndexRoute
  '/tenant': typeof TenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/landlord/documents': typeof LandlordDocumentsRoute
  '/landlord/financials': typeof LandlordFinancialsRoute
  '/landlord/properties': typeof LandlordPropertiesRoute
  '/landlord/tenants': typeof LandlordTenantsRoute
  '/manager/documents': typeof ManagerDocumentsRoute
  '/manager/emails': typeof ManagerEmailsRoute
  '/manager/financials': typeof ManagerFinancialsRoute
  '/manager/maintenance': typeof ManagerMaintenanceRoute
  '/manager/notifications': typeof ManagerNotificationsRoute
  '/manager/properties': typeof ManagerPropertiesRoute
  '/manager/reports': typeof ManagerReportsRoute
  '/manager/settings': typeof ManagerSettingsRoute
  '/manager/tenants': typeof ManagerTenantsRoute
  '/tenant/documents': typeof TenantDocumentsRoute
  '/tenant/loan': typeof TenantLoanRoute
  '/tenant/maintenance': typeof TenantMaintenanceRoute
  '/tenant/rent': typeof TenantRentRoute
  '/tenant/reviews': typeof TenantReviewsRoute
  '/landlord/': typeof LandlordIndexRoute
  '/manager/': typeof ManagerIndexRoute
  '/tenant/': typeof TenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/landlord/documents'
    | '/landlord/financials'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/manager/documents'
    | '/manager/emails'
    | '/manager/financials'
    | '/manager/maintenance'
    | '/manager/notifications'
    | '/manager/properties'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/tenants'
    | '/tenant/documents'
    | '/tenant/loan'
    | '/tenant/maintenance'
    | '/tenant/rent'
    | '/tenant/reviews'
    | '/landlord/'
    | '/manager/'
    | '/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/landlord/documents'
    | '/landlord/financials'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/manager/documents'
    | '/manager/emails'
    | '/manager/financials'
    | '/manager/maintenance'
    | '/manager/notifications'
    | '/manager/properties'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/tenants'
    | '/tenant/documents'
    | '/tenant/loan'
    | '/tenant/maintenance'
    | '/tenant/rent'
    | '/tenant/reviews'
    | '/landlord'
    | '/manager'
    | '/tenant'
  id:
    | '__root__'
    | '/'
    | '/landlord/documents'
    | '/landlord/financials'
    | '/landlord/properties'
    | '/landlord/tenants'
    | '/manager/documents'
    | '/manager/emails'
    | '/manager/financials'
    | '/manager/maintenance'
    | '/manager/notifications'
    | '/manager/properties'
    | '/manager/reports'
    | '/manager/settings'
    | '/manager/tenants'
    | '/tenant/documents'
    | '/tenant/loan'
    | '/tenant/maintenance'
    | '/tenant/rent'
    | '/tenant/reviews'
    | '/landlord/'
    | '/manager/'
    | '/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LandlordDocumentsRoute: typeof LandlordDocumentsRoute
  LandlordFinancialsRoute: typeof LandlordFinancialsRoute
  LandlordPropertiesRoute: typeof LandlordPropertiesRoute
  LandlordTenantsRoute: typeof LandlordTenantsRoute
  ManagerDocumentsRoute: typeof ManagerDocumentsRoute
  ManagerEmailsRoute: typeof ManagerEmailsRoute
  ManagerFinancialsRoute: typeof ManagerFinancialsRoute
  ManagerMaintenanceRoute: typeof ManagerMaintenanceRoute
  ManagerNotificationsRoute: typeof ManagerNotificationsRoute
  ManagerPropertiesRoute: typeof ManagerPropertiesRoute
  ManagerReportsRoute: typeof ManagerReportsRoute
  ManagerSettingsRoute: typeof ManagerSettingsRoute
  ManagerTenantsRoute: typeof ManagerTenantsRoute
  TenantDocumentsRoute: typeof TenantDocumentsRoute
  TenantLoanRoute: typeof TenantLoanRoute
  TenantMaintenanceRoute: typeof TenantMaintenanceRoute
  TenantRentRoute: typeof TenantRentRoute
  TenantReviewsRoute: typeof TenantReviewsRoute
  LandlordIndexRoute: typeof LandlordIndexRoute
  ManagerIndexRoute: typeof ManagerIndexRoute
  TenantIndexRoute: typeof TenantIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/': {
      id: '/tenant/'
      path: '/tenant'
      fullPath: '/tenant/'
      preLoaderRoute: typeof TenantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/': {
      id: '/manager/'
      path: '/manager'
      fullPath: '/manager/'
      preLoaderRoute: typeof ManagerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/': {
      id: '/landlord/'
      path: '/landlord'
      fullPath: '/landlord/'
      preLoaderRoute: typeof LandlordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/reviews': {
      id: '/tenant/reviews'
      path: '/tenant/reviews'
      fullPath: '/tenant/reviews'
      preLoaderRoute: typeof TenantReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/rent': {
      id: '/tenant/rent'
      path: '/tenant/rent'
      fullPath: '/tenant/rent'
      preLoaderRoute: typeof TenantRentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/maintenance': {
      id: '/tenant/maintenance'
      path: '/tenant/maintenance'
      fullPath: '/tenant/maintenance'
      preLoaderRoute: typeof TenantMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/loan': {
      id: '/tenant/loan'
      path: '/tenant/loan'
      fullPath: '/tenant/loan'
      preLoaderRoute: typeof TenantLoanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/documents': {
      id: '/tenant/documents'
      path: '/tenant/documents'
      fullPath: '/tenant/documents'
      preLoaderRoute: typeof TenantDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/tenants': {
      id: '/manager/tenants'
      path: '/manager/tenants'
      fullPath: '/manager/tenants'
      preLoaderRoute: typeof ManagerTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/settings': {
      id: '/manager/settings'
      path: '/manager/settings'
      fullPath: '/manager/settings'
      preLoaderRoute: typeof ManagerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/reports': {
      id: '/manager/reports'
      path: '/manager/reports'
      fullPath: '/manager/reports'
      preLoaderRoute: typeof ManagerReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/properties': {
      id: '/manager/properties'
      path: '/manager/properties'
      fullPath: '/manager/properties'
      preLoaderRoute: typeof ManagerPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/notifications': {
      id: '/manager/notifications'
      path: '/manager/notifications'
      fullPath: '/manager/notifications'
      preLoaderRoute: typeof ManagerNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/maintenance': {
      id: '/manager/maintenance'
      path: '/manager/maintenance'
      fullPath: '/manager/maintenance'
      preLoaderRoute: typeof ManagerMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/financials': {
      id: '/manager/financials'
      path: '/manager/financials'
      fullPath: '/manager/financials'
      preLoaderRoute: typeof ManagerFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/emails': {
      id: '/manager/emails'
      path: '/manager/emails'
      fullPath: '/manager/emails'
      preLoaderRoute: typeof ManagerEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/manager/documents': {
      id: '/manager/documents'
      path: '/manager/documents'
      fullPath: '/manager/documents'
      preLoaderRoute: typeof ManagerDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/tenants': {
      id: '/landlord/tenants'
      path: '/landlord/tenants'
      fullPath: '/landlord/tenants'
      preLoaderRoute: typeof LandlordTenantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/properties': {
      id: '/landlord/properties'
      path: '/landlord/properties'
      fullPath: '/landlord/properties'
      preLoaderRoute: typeof LandlordPropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/financials': {
      id: '/landlord/financials'
      path: '/landlord/financials'
      fullPath: '/landlord/financials'
      preLoaderRoute: typeof LandlordFinancialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landlord/documents': {
      id: '/landlord/documents'
      path: '/landlord/documents'
      fullPath: '/landlord/documents'
      preLoaderRoute: typeof LandlordDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LandlordDocumentsRoute: LandlordDocumentsRoute,
  LandlordFinancialsRoute: LandlordFinancialsRoute,
  LandlordPropertiesRoute: LandlordPropertiesRoute,
  LandlordTenantsRoute: LandlordTenantsRoute,
  ManagerDocumentsRoute: ManagerDocumentsRoute,
  ManagerEmailsRoute: ManagerEmailsRoute,
  ManagerFinancialsRoute: ManagerFinancialsRoute,
  ManagerMaintenanceRoute: ManagerMaintenanceRoute,
  ManagerNotificationsRoute: ManagerNotificationsRoute,
  ManagerPropertiesRoute: ManagerPropertiesRoute,
  ManagerReportsRoute: ManagerReportsRoute,
  ManagerSettingsRoute: ManagerSettingsRoute,
  ManagerTenantsRoute: ManagerTenantsRoute,
  TenantDocumentsRoute: TenantDocumentsRoute,
  TenantLoanRoute: TenantLoanRoute,
  TenantMaintenanceRoute: TenantMaintenanceRoute,
  TenantRentRoute: TenantRentRoute,
  TenantReviewsRoute: TenantReviewsRoute,
  LandlordIndexRoute: LandlordIndexRoute,
  ManagerIndexRoute: ManagerIndexRoute,
  TenantIndexRoute: TenantIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
